version: '3.8'
services:
  nodeapp:
    build: .
    ports:
      - "3000:3000"
    # environment:
    #   - MONGO_URL=mongodb://mongodb:27017/mydb
    # depends_on:
    #   - mongodb
    networks:
      - app-network

#   mongodb:
#     image: mongo:latest
#     volumes:
#       - mongodb-data:/data/db
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=mongoadmin
#       - MONGO_INITDB_ROOT_PASSWORD=secret
#     networks:
#       - app-network

# volumes:
#   mongodb-data:

networks:
  app-network:
